services: 
  nginx:
    volumes:
      - ./nginx/nginx.frontend.dev.conf:/etc/nginx/nginx.frontend.conf:ro


  frontend:
    volumes:
      - ./frontend:/app

    restart: always

    ports: 
      - 3000:3000

    command: "npm run dev"

    
  backend:
    volumes:
      - ./backend/src:/backend_service/src

    command: bash -c "poetry run alembic upgrade head && cd src && poetry run uvicorn app.main.app:app --reload --workers 1 --host 0.0.0.0 --port 8000"


  auth:
    volumes:
      - ./auth/src:/auth_service/src

    command: bash -c "poetry run alembic upgrade head && cd src && poetry run uvicorn app.main.app:app --reload --workers 1 --host 0.0.0.0 --port 8000"


  files:
    volumes:
      - ./files/src:/files_service/src

    command: bash -c "poetry run alembic upgrade head && cd src && poetry run uvicorn app.main.app:app --reload --workers 1 --host 0.0.0.0 --port 8000"
