services:

  nginx:
    container_name: nginx

    environment:
      - IP_NGINX=${IP_NGINX}

    build:
      context: ./nginx
      dockerfile: Dockerfile

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.conf.template:/etc/nginx/default.conf.template

    command: > 
      bash -c "envsubst < /etc/nginx/default.conf.template > /etc/nginx/sites-available/${IP_NGINX}.conf
      && ln -sf /etc/nginx/sites-available/${IP_NGINX}.conf /etc/nginx/sites-enabled/
      && nginx -g 'daemon off;'"

    ports:
      - 80:80

    networks:
      - infosystem_net

    depends_on:
      - backend
      - auth
 
  certbot:
    ports:
      - 6000:80
      
    volumes:
      - ./nginx:/etc/nginx

    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN: ${DOMAIN}
        API_DOMAIN: ${API_DOMAIN}

    networks:
      - infosystem_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend

    restart: always

    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=rhi
      - USER=${USER}
      - PORT=5432
      - MODE=PROD
      - HOST=db

    ports: 
      - 8000:8000

    networks:
      - infosystem_net

    depends_on:
      - db
    
    command: bash -c "alembic upgrade head && uvicorn src.app:app --workers 1 --host 0.0.0.0 --port 8000"

  db:
    container_name: db
    restart: always
    image: postgres:16.3-alpine3.20

    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=rhi
      - PGDATA=/var/lib/postgresql/data/

    ports:
      - 5433:5432

    volumes:
      - backend_data:/var/lib/postgresql

    networks:
      - infosystem_net

    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "rhi", "-U", "${USER}" ]
      timeout: 3s
      retries: 5

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile

    container_name: auth

    restart: always
    
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - AUTH_DATABASE_NAME=rhi_auth
      - SECRET_KEY=${SECRET_KEY}
      - AUTH_HOST=auth_db
      - USER=${USER}
      - PORT=5432
      - MODE=PROD

    ports: 
      - 8001:8000

    networks:
      - infosystem_net

    depends_on:
      - auth_db

    command: bash -c "alembic upgrade head && uvicorn src.app:app --workers 1 --host 0.0.0.0 --port 8000"

  auth_db:
    container_name: auth_db
    restart: always
    image: postgres:16.3-alpine3.20

    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=rhi_auth
      - PGDATA=/var/lib/postgresql/data/

    ports:
      - 5434:5432

    networks:
      - infosystem_net

    volumes:
      - auth_data:/var/lib/postgresql

    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "rhi_auth", "-U", "${USER}" ]
      timeout: 3s
      retries: 5


volumes:
  backend_data:
  auth_data:


networks:
  infosystem_net:
