services:

  nginx:
    image: nginx:1.27.0-alpine3.19

    container_name: nginx

    environment:
      - IP_NGINX=${IP_NGINX}

    build:
      context: ./nginx
      dockerfile: Dockerfile

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.conf.template:/etc/nginx/default.conf.template

    command: > 
      bash -c "envsubst < /etc/nginx/default.conf.template > /etc/nginx/sites-available/${IP_NGINX}.conf
      && ln -sf /etc/nginx/sites-available/${IP_NGINX}.conf /etc/nginx/sites-enabled/
      && nginx -g 'daemon off;'"

    ports:
      - 80:80

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend

    restart: always

    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=rhi
      - USER=${USER}
      - PORT=5432
      - MODE=PROD
      - HOST=db

    ports: 
      - 8000:8000

    depends_on:
      - db
    
    command: bash -c "alembic upgrade head && uvicorn src.app:app --workers 1 --host 0.0.0.0 --port 8000"

  db:
    container_name: db
    restart: always
    image: postgres:16.3-alpine3.20

    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=rhi
      - PGDATA=/var/lib/postgresql/data/

    ports:
      - 5433:5432

    volumes:
      - backend_db_data:/var/lib/postgresql

    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "rhi", "-U", "${USER}" ]
      timeout: 3s
      retries: 5


volumes:
  backend_db_data:
