services:

  nginx:
    image: nginx:1.27.0-alpine3.19
    container_name: nginx

    ports:
      - 80:80

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend

    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=rhi
      - USER=${USER}
      - PORT=5432
      - MODE=PROD
      - HOST=db

    ports: 
      - 8000:8000

    depends_on:
      - db
    
    command: bash -c "alembic upgrade head && uvicorn src.app:app --workers 1 --host 0.0.0.0 --port 8000"

  db:
    container_name: db
    restart: always
    image: postgres:16.3-alpine3.20

    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=rhi
      - PGDATA=/var/lib/postgresql/data/

    ports:
      - 5433:5432

    volumes:
      - /var/lib/postgresql:/var/lib/postgresql

    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "rhi", "-U", "${USER}" ]
      timeout: 3s
      retries: 5
