services: 
  nginx:
    volumes:
      - ./nginx/nginx.frontend.conf:/etc/nginx/nginx.frontend.conf:ro
      - /var/www/naks-infosystem/dist:/var/www/naks-infosystem/dist


  frontend:
    volumes:
      - /var/www/naks-infosystem/dist:/app/dist

    command: "npm run build --mode production"
